spring:
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true
  h2:
    console.enabled: true

  graphql:
    jpa:
      query:
        name: BooksRelay
        description: GraphQL Jpa Query Books Relay Example
        enable-relay: true
        enabled: true

logging:
  level:
    com.introproventures.graphql.jpa.query.schema: DEBUG
    